---
title: "ICD Special Issue -- Planning"
author: "Rick Gilmore & Yiming Qian"
date: "`r Sys.time()`"
output: html_document
---

# Purpose

This document documents the planning process that Rick Gilmore & Yiming Qian underwent in writing an essay for a special issue in *Infant and Child Development* on the topic "Current Perspectives in Developmental Science."

# Scope

- ~2,000 words of main text
- Due end of March 2021
- Preprint on PsyArXiv recommended

# Ideas

- Developmental science is harder than physics
- Developmental science can be
  - more rigorous
  - more robust
  - more open
  - more reproducible
  - integrable, incremental in a positive and constructive way
- Wishlist
  - greater diversity of participants
  - data a first-class scholarly product
  - all data shared in forms that permit easy verification of main findings
    - openly shared, scriptable analysis pipelines
    - well-curated
    - standardized metadata with schema
    - accessible via scriptable APIs
  - gradual end to the use of proprietary measurement instruments
    - future where item-level data can be combined across measures
  - increased use and sharing of video and audio as data
    - permits richer descriptions of behaviors, contexts
  - greater clarity about presumed causal models